//TONYWN1 JOB (NFSD),'MAKE DINO-NFS',
//      CLASS=A,MSGCLASS=X,MSGLEVEL=1,REGION=8M,
//      NOTIFY=TONYW
//*
//********************************************************************
//*
//* NAME: MAKENFSD
//*
//* DESC: COMPILE AND LINK DINO NFSD, USING JCC COMPILER
//*
//********************************************************************
//JCCCMOD PROC SOUT='*',JCC='JCC',
//          INFILE='TONYW.DINONFS.C',
//          OBJFILE='TONYW.DINONFS.OBJLIB',
//          HDRFILE='TONYW.DINONFS.H',
//          JOPTS='-O -LIST=//DDN:SYSPRINT -D__MVS__',
//          MODNAME='NOT-SPECIFIED'
//*
//COMPILE  EXEC PGM=JCC,
//         PARM='-I//DDN:JCCINCL //DDN:SYSIN &JOPTS'
//STEPLIB  DD   DSN=&JCC..LINKLIB,DISP=SHR
//SYSPRINT DD   SYSOUT=&SOUT
//JCCINCL  DD   DSN=&JCC..INCLUDE,DISP=SHR
//JCCINCS  DD   DISP=SHR,DSN=&HDRFILE
//JCCOUTPT DD   UNIT=SYSDA,SPACE=(TRK,(50,20)),DISP=(,DELETE),
//         DSN=&&OUTPT
//STDOUT   DD   SYSOUT=&SOUT
//JCCOASM  DD   DISP=SHR,DSN=&OBJFILE(&MODNAME)
//SYSIN    DD   DSN=&INFILE(&MODNAME),DISP=SHR
//*
//JCCCMOD  PEND
//*
//********************************************************************
//*
//* COMPILE MODULES
//*
//********************************************************************
//EBCDIC   EXEC JCCCMOD,MODNAME=EBCDIC
//EXPORTS  EXEC JCCCMOD,MODNAME=EXPORTS
//FHANDLE  EXEC JCCCMOD,MODNAME=FHANDLE
//MOUNT3   EXEC JCCCMOD,MODNAME=MOUNT3
//MVSFID   EXEC JCCCMOD,MODNAME=MVSFID
//NFS3     EXEC JCCCMOD,MODNAME=NFS3
//PORTMAP  EXEC JCCCMOD,MODNAME=PORTMAP
//RPC      EXEC JCCCMOD,MODNAME=RPC
//VFS      EXEC JCCCMOD,MODNAME=VFS
//XDR      EXEC JCCCMOD,MODNAME=XDR
//*
//********************************************************************
//*
//* COMPILE AND LINK MAIN NFSD
//*
//********************************************************************
//NFSD    EXEC JCCCL,INFILE='TONYW.DINONFS.C(NFSD)',
//        OUTFILE='TONYW.DINONFS.LOAD(NFSD)',
//        JOPTS='-O -LIST=//DDN:SYSPRINT -D__MVS__'
//COMPILE.JCCINCS DD DISP=SHR,DSN=TONYW.DINONFS.H
//PRELINK.L DD DSN=&&ALLOBJ,DISP=(OLD,DELETE)
//PRELINK.I DD DISP=SHR,DSN=TONYW.DINONFS.OBJLIB(EBCDIC)
//          DD DISP=SHR,DSN=TONYW.DINONFS.OBJLIB(EXPORTS)
//          DD DISP=SHR,DSN=TONYW.DINONFS.OBJLIB(FHANDLE)
//          DD DISP=SHR,DSN=TONYW.DINONFS.OBJLIB(MOUNT3)
//          DD DISP=SHR,DSN=TONYW.DINONFS.OBJLIB(MVSFID)
//          DD DISP=SHR,DSN=TONYW.DINONFS.OBJLIB(NFS3)
//          DD DISP=SHR,DSN=TONYW.DINONFS.OBJLIB(PORTMAP)
//          DD DISP=SHR,DSN=TONYW.DINONFS.OBJLIB(RPC)
//          DD DISP=SHR,DSN=TONYW.DINONFS.OBJLIB(VFS)
//          DD DISP=SHR,DSN=TONYW.DINONFS.OBJLIB(XDR)
//          DD DSN=&&OBJ,DISP=(OLD,DELETE)
//
